# Generated by Django 5.0.1 on 2024-04-20 14:16

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skis',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='first.product')),
                ('rost', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('ridingstyle', models.CharField(max_length=20)),
                ('leveloftraining', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'skis',
            },
        ),
        migrations.CreateModel(
            name='snowboard',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='first.product')),
                ('rost', models.CharField(max_length=20)),
                ('zhest', models.CharField(max_length=20)),
                ('progib', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'snowboards',
            },
        ),
        migrations.RenameModel(
            old_name='ProductInCart',
            new_name='ProductInTheCart',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(8.0), django.core.validators.MinValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='progib',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='rost',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='snowboard', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='zhest',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='user_default.png', upload_to='user_img/'),
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.coment')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratingtabls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
