# Generated by Django 5.0.1 on 2024-04-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_skis_snowboard_rename_productincart_productinthecart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
